# Generated by Django 5.2.6 on 2025-09-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the pet's name", max_length=100)),
                ('breed', models.CharField(help_text="Enter the pet's breed", max_length=100)),
                ('age', models.PositiveIntegerField(help_text="Enter the pet's age in years")),
                ('description', models.TextField(help_text='Provide a detailed description of the pet')),
                ('adopted', models.BooleanField(default=False, help_text='Check if the pet has been adopted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['-created_at'],
            },
        ),
    ]
