# Generated by Django 5.2.6 on 2025-09-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo of the pet', null=True, upload_to='pet_images/'),
        ),
    ]
